  - name: "Stop SYSTEM"
    debug: msg="Stopping SYSTEM"

  - name: "Get Current Session Id"
    win_shell: |
      $server = "localhost"
      $users = @()
      # Query using quser, 2>$null to hide "No users exists...", then skip to the next server
      $quser = quser /server:$server 2>$null
      if(!($quser)){
          Continue
      }
      #Remove column headers
      $quser = $quser[1..$($quser.Count)]
      foreach($user in $quser){
        $usersObj = [PSCustomObject]@{SessionId=$Null}
        $quserData = $user -split "\s+"
        #We have to splice the array if the session is disconnected (as the SESSIONNAME column quserData[2] is empty)
        if(($user | select-string "{{ psexec_service_user.split('@')[0] }}") -eq $null){
            Continue
        }
        #We have to splice the array if the session is disconnected (as the SESSIONNAME column quserData[2] is empty)
        if(($user | select-string "Disc") -ne $null){
            #User is disconnected
            $quserData = ($quserData[0..1],"null",$quserData[2..($quserData.Length -1)]) -split "\s+"
        }
        # SessionID
        $users = $quserData[3]
      }
      return $users
    register: current_session_id

  - name: "( STOP - SYSTEM ) - Stop SYSTEM instance"
    win_command: "{{ tools_path }}{{ path_separator }}PSTools{{ path_separator }}PSExec64.exe -accepteula -nobanner -h -s -i {{ current_session_id.stdout | int }} cmd /c start {{ project_root }}{{ path_separator }}current{{ path_separator }}system{{ path_separator }}check_system.bat"
    register: system_stopped_bat