  - name: "Start WEB"
    debug: msg="Starting WEB"

  - name: "Get Current Session Id"
    win_shell: |
      $server = "localhost"
      $users = @()
      # Query using quser, 2>$null to hide "No users exists...", then skip to the next server
      $quser = quser /server:$server 2>$null
      if(!($quser)){
          Continue
      }
      #Remove column headers
      $quser = $quser[1..$($quser.Count)]
      foreach($user in $quser){
        $usersObj = [PSCustomObject]@{SessionId=$Null}
        $quserData = $user -split "\s+"
        #We have to splice the array if the session is disconnected (as the SESSIONNAME column quserData[2] is empty)
        if(($user | select-string "{{ psexec_service_user.split('@')[0] }}") -eq $null){
            Continue
        }
        #We have to splice the array if the session is disconnected (as the SESSIONNAME column quserData[2] is empty)
        if(($user | select-string "Disc") -ne $null){
            #User is disconnected
            $quserData = ($quserData[0..1],"null",$quserData[2..($quserData.Length -1)]) -split "\s+"
        }
        # SessionID
        $users = $quserData[3]
      }
      return $users
    register: current_session_id

  - name: "Start WEB service"
    win_command: "{{ tools_path }}{{ path_separator }}PSTools{{ path_separator }}PSExec64.exe -accepteula -nobanner -h -s -w {{ project_root }}\\current\\web -i {{ current_session_id.stdout | int }} cmd /c start {{ project_root }}\\current\\web\\run_web.bat"

  - name: "Wait to ensure service is working"
    win_wait_for:
      port: "{{ pricing_web_akka_port | default('2550') }}"
      delay: 10
      retries: 30
      state: started